# Generated by Django 5.0.4 on 2024-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Feverydayicons.jp%2Ficons%2Ftag%2F%25E3%2582%25A2%25E3%2583%2590%25E3%2582%25BF%25E3%2583%25BC%2F&psig=AOvVaw2r0V2i9L_kTnQ_COeNy_EY&ust=1711626088288000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKDbw5mulIUDFQAAAAAdAAAAABAE', null=True, upload_to='img/'),
        ),
    ]
