# Generated by Django 5.0.4 on 2024-04-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='img/'),
        ),
    ]
