# Generated by Django 5.0.3 on 2024-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_message_options_remove_customuser_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Feverydayicons.jp%2Ficons%2Ftag%2F%25E3%2582%25A2%25E3%2583%2590%25E3%2582%25BF%25E3%2583%25BC%2F&psig=AOvVaw2r0V2i9L_kTnQ_COeNy_EY&ust=1711626088288000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKDbw5mulIUDFQAAAAAdAAAAABAE', upload_to='img/'),
        ),
    ]
